language: python
python:
- '3.7'


language: python
python:
- '3.7'
env:
- SERVER_IP_ADDRESS=138.68.189.32
branches:
  only:
  - A
  - main
install:
- python -m pip install --upgrade pip
- pip install --upgrade setuptools
- pip install wheel --no-cache
- pip install -r requirements.txt
- pip install psycopg2-binary
- pip install --upgrade setuptools
- pip install Flask-JWT-Extended
- pip install blinker
- pip install python-multipart
- pip install fastapi
script:
- python -m unittest tests/test_port.py